buildscript {
    ext.kotlin_version = '1.9.24'

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.release = 17
        }
    }
}
